# fly.toml app configuration file generated for cool-frog-8691 on 2023-07-15T21:46:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cool-frog-8691"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
